version: "3.9"

services:
  app:
    container_name: anthorflix-front
    image: dannyfranca/anthorflix-front
    build:
      context: .
      target: production
    ports:
      - '3000:80'
    environment:
      - REACT_APP_PUBLIC_URL=http://localhost:4000
