version: "3.9"

services:
  app:
    image: dannyfranca/anthorflix-front
    container_name: anthorflix-front
    restart: on-failure
    build:
      context: .
    depends_on:
      - anthorflix-api
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_PUBLIC_URL=http://localhost:4000
    networks:
      - app-net

  anthorflix-api:
    image: 'dannyfranca/anthorflix-api'
    container_name: anthorflix-api
    hostname: anthorflix-api
    restart: on-failure
    pull_policy: if_not_present
    depends_on:
      - postgres
    ports:
      - '4000:80'
    environment:
      - NODE_ENV=production
      - PORT=80
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/anthorflix?schema=public
    networks:
      - app-net

  postgres:
    image: 'bitnami/postgresql'
    container_name: postgres
    hostname: postgres
    restart: always
    expose:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=anthorflix
    volumes:
      - 'postgresql:/bitnami/postgresql'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql:
