export const ptBrTranslations: { [k: string]: string } = {
  Dashboard: "Painel",
  Name: "Nome",
  Title: "Título",
  Description: "Descrição",
  Active: "Ativo",
  "Created at": "Criado em",
  Save: "Salvar",
  List: "Listar",
  Add: "Adicionar",
  Create: "Criar",
  Edit: "Editar",
  Import: "Importar",
  Soon: "Em breve",
  "Save and continue editing": "Salvar e continuar editando",
  "saved with success": "salvo com sucesso",
  // ENTITIES
  Movie: "Filme",
  Movies: "Filmes",
  Year: "Ano",
  Synopsis: "Sinopse",
  Genre: "Gênero",
  Genres: "Gêneros",
  "Cast member": "Participante",
  "Cast members": "Participantes",
  // DATA TABLE
  "No match records found": "Nenhum registro encontrado",
  Sort: "Classificar",
  "Next page": "Próxima página",
  "Previous page": "Página anterior",
  "Rows per page:": "Linhas por página:",
  of: "de",
  Search: "Buscar",
  "Download CSV": "Download CSV",
  Print: "Imprimir",
  "View Columns": "Ver Colunas",
  "Filter Table": "Filtrar Tabelas",
  All: "Todos",
  Filters: "Filtros",
  Reset: "Limpar",
  "Show table columns": "Ver/Esconder colunas da tabela",
  "row(s) selected": "registros(s) selecionados",
  Delete: "Deletar",
  "Delete selected columns": "Deletar colunas selecionadas",
  Actions: "Ações",
  Loading: "Carregando",
  "Unable to load data": "Não foi possível carregar as informações",
  "Clear search": "Limpar busca",
};
